#ifndef PROTOCOL_READER_H
#define PROTOCOL_READER_H

/* Generated by flatcc 0.5.3-pre FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif


typedef const struct Ckb_Protocol_SyncMessage_table *Ckb_Protocol_SyncMessage_table_t;
typedef const flatbuffers_uoffset_t *Ckb_Protocol_SyncMessage_vec_t;
typedef flatbuffers_uoffset_t *Ckb_Protocol_SyncMessage_mutable_vec_t;
typedef const struct Ckb_Protocol_Bytes_table *Ckb_Protocol_Bytes_table_t;
typedef const flatbuffers_uoffset_t *Ckb_Protocol_Bytes_vec_t;
typedef flatbuffers_uoffset_t *Ckb_Protocol_Bytes_mutable_vec_t;
typedef const struct Ckb_Protocol_GetHeaders_table *Ckb_Protocol_GetHeaders_table_t;
typedef const flatbuffers_uoffset_t *Ckb_Protocol_GetHeaders_vec_t;
typedef flatbuffers_uoffset_t *Ckb_Protocol_GetHeaders_mutable_vec_t;
typedef const struct Ckb_Protocol_GetBlocks_table *Ckb_Protocol_GetBlocks_table_t;
typedef const flatbuffers_uoffset_t *Ckb_Protocol_GetBlocks_vec_t;
typedef flatbuffers_uoffset_t *Ckb_Protocol_GetBlocks_mutable_vec_t;
typedef const struct Ckb_Protocol_Headers_table *Ckb_Protocol_Headers_table_t;
typedef const flatbuffers_uoffset_t *Ckb_Protocol_Headers_vec_t;
typedef flatbuffers_uoffset_t *Ckb_Protocol_Headers_mutable_vec_t;
typedef const struct Ckb_Protocol_Header_table *Ckb_Protocol_Header_table_t;
typedef const flatbuffers_uoffset_t *Ckb_Protocol_Header_vec_t;
typedef flatbuffers_uoffset_t *Ckb_Protocol_Header_mutable_vec_t;
typedef const struct Ckb_Protocol_Block_table *Ckb_Protocol_Block_table_t;
typedef const flatbuffers_uoffset_t *Ckb_Protocol_Block_vec_t;
typedef flatbuffers_uoffset_t *Ckb_Protocol_Block_mutable_vec_t;
typedef const struct Ckb_Protocol_UncleBlock_table *Ckb_Protocol_UncleBlock_table_t;
typedef const flatbuffers_uoffset_t *Ckb_Protocol_UncleBlock_vec_t;
typedef flatbuffers_uoffset_t *Ckb_Protocol_UncleBlock_mutable_vec_t;
typedef const struct Ckb_Protocol_Transaction_table *Ckb_Protocol_Transaction_table_t;
typedef const flatbuffers_uoffset_t *Ckb_Protocol_Transaction_vec_t;
typedef flatbuffers_uoffset_t *Ckb_Protocol_Transaction_mutable_vec_t;
typedef const struct Ckb_Protocol_OutPoint_table *Ckb_Protocol_OutPoint_table_t;
typedef const flatbuffers_uoffset_t *Ckb_Protocol_OutPoint_vec_t;
typedef flatbuffers_uoffset_t *Ckb_Protocol_OutPoint_mutable_vec_t;
typedef const struct Ckb_Protocol_CellInput_table *Ckb_Protocol_CellInput_table_t;
typedef const flatbuffers_uoffset_t *Ckb_Protocol_CellInput_vec_t;
typedef flatbuffers_uoffset_t *Ckb_Protocol_CellInput_mutable_vec_t;
typedef const struct Ckb_Protocol_CellOutput_table *Ckb_Protocol_CellOutput_table_t;
typedef const flatbuffers_uoffset_t *Ckb_Protocol_CellOutput_vec_t;
typedef flatbuffers_uoffset_t *Ckb_Protocol_CellOutput_mutable_vec_t;
typedef const struct Ckb_Protocol_Script_table *Ckb_Protocol_Script_table_t;
typedef const flatbuffers_uoffset_t *Ckb_Protocol_Script_vec_t;
typedef flatbuffers_uoffset_t *Ckb_Protocol_Script_mutable_vec_t;
typedef const struct Ckb_Protocol_RelayMessage_table *Ckb_Protocol_RelayMessage_table_t;
typedef const flatbuffers_uoffset_t *Ckb_Protocol_RelayMessage_vec_t;
typedef flatbuffers_uoffset_t *Ckb_Protocol_RelayMessage_mutable_vec_t;
typedef const struct Ckb_Protocol_CompactBlock_table *Ckb_Protocol_CompactBlock_table_t;
typedef const flatbuffers_uoffset_t *Ckb_Protocol_CompactBlock_vec_t;
typedef flatbuffers_uoffset_t *Ckb_Protocol_CompactBlock_mutable_vec_t;
typedef const struct Ckb_Protocol_PrefilledTransaction_table *Ckb_Protocol_PrefilledTransaction_table_t;
typedef const flatbuffers_uoffset_t *Ckb_Protocol_PrefilledTransaction_vec_t;
typedef flatbuffers_uoffset_t *Ckb_Protocol_PrefilledTransaction_mutable_vec_t;
typedef const struct Ckb_Protocol_GetBlockTransactions_table *Ckb_Protocol_GetBlockTransactions_table_t;
typedef const flatbuffers_uoffset_t *Ckb_Protocol_GetBlockTransactions_vec_t;
typedef flatbuffers_uoffset_t *Ckb_Protocol_GetBlockTransactions_mutable_vec_t;
typedef const struct Ckb_Protocol_BlockTransactions_table *Ckb_Protocol_BlockTransactions_table_t;
typedef const flatbuffers_uoffset_t *Ckb_Protocol_BlockTransactions_vec_t;
typedef flatbuffers_uoffset_t *Ckb_Protocol_BlockTransactions_mutable_vec_t;
typedef const struct Ckb_Protocol_GetBlockProposal_table *Ckb_Protocol_GetBlockProposal_table_t;
typedef const flatbuffers_uoffset_t *Ckb_Protocol_GetBlockProposal_vec_t;
typedef flatbuffers_uoffset_t *Ckb_Protocol_GetBlockProposal_mutable_vec_t;
typedef const struct Ckb_Protocol_BlockProposal_table *Ckb_Protocol_BlockProposal_table_t;
typedef const flatbuffers_uoffset_t *Ckb_Protocol_BlockProposal_vec_t;
typedef flatbuffers_uoffset_t *Ckb_Protocol_BlockProposal_mutable_vec_t;
#ifndef Ckb_Protocol_SyncMessage_identifier
#define Ckb_Protocol_SyncMessage_identifier flatbuffers_identifier
#endif
#define Ckb_Protocol_SyncMessage_type_hash ((flatbuffers_thash_t)0x1e5b73cf)
#define Ckb_Protocol_SyncMessage_type_identifier "\xcf\x73\x5b\x1e"
#ifndef Ckb_Protocol_Bytes_identifier
#define Ckb_Protocol_Bytes_identifier flatbuffers_identifier
#endif
#define Ckb_Protocol_Bytes_type_hash ((flatbuffers_thash_t)0xd1424a)
#define Ckb_Protocol_Bytes_type_identifier "\x4a\x42\xd1\x00"
#ifndef Ckb_Protocol_GetHeaders_identifier
#define Ckb_Protocol_GetHeaders_identifier flatbuffers_identifier
#endif
#define Ckb_Protocol_GetHeaders_type_hash ((flatbuffers_thash_t)0x45805aad)
#define Ckb_Protocol_GetHeaders_type_identifier "\xad\x5a\x80\x45"
#ifndef Ckb_Protocol_GetBlocks_identifier
#define Ckb_Protocol_GetBlocks_identifier flatbuffers_identifier
#endif
#define Ckb_Protocol_GetBlocks_type_hash ((flatbuffers_thash_t)0x29433447)
#define Ckb_Protocol_GetBlocks_type_identifier "\x47\x34\x43\x29"
#ifndef Ckb_Protocol_Headers_identifier
#define Ckb_Protocol_Headers_identifier flatbuffers_identifier
#endif
#define Ckb_Protocol_Headers_type_hash ((flatbuffers_thash_t)0x6a8e30df)
#define Ckb_Protocol_Headers_type_identifier "\xdf\x30\x8e\x6a"
#ifndef Ckb_Protocol_Header_identifier
#define Ckb_Protocol_Header_identifier flatbuffers_identifier
#endif
#define Ckb_Protocol_Header_type_hash ((flatbuffers_thash_t)0x3bf6d376)
#define Ckb_Protocol_Header_type_identifier "\x76\xd3\xf6\x3b"
#ifndef Ckb_Protocol_Block_identifier
#define Ckb_Protocol_Block_identifier flatbuffers_identifier
#endif
#define Ckb_Protocol_Block_type_hash ((flatbuffers_thash_t)0x7dca81f0)
#define Ckb_Protocol_Block_type_identifier "\xf0\x81\xca\x7d"
#ifndef Ckb_Protocol_UncleBlock_identifier
#define Ckb_Protocol_UncleBlock_identifier flatbuffers_identifier
#endif
#define Ckb_Protocol_UncleBlock_type_hash ((flatbuffers_thash_t)0x64c6e4b)
#define Ckb_Protocol_UncleBlock_type_identifier "\x4b\x6e\x4c\x06"
#ifndef Ckb_Protocol_Transaction_identifier
#define Ckb_Protocol_Transaction_identifier flatbuffers_identifier
#endif
#define Ckb_Protocol_Transaction_type_hash ((flatbuffers_thash_t)0x67bc25a1)
#define Ckb_Protocol_Transaction_type_identifier "\xa1\x25\xbc\x67"
#ifndef Ckb_Protocol_OutPoint_identifier
#define Ckb_Protocol_OutPoint_identifier flatbuffers_identifier
#endif
#define Ckb_Protocol_OutPoint_type_hash ((flatbuffers_thash_t)0xfbbcc2ed)
#define Ckb_Protocol_OutPoint_type_identifier "\xed\xc2\xbc\xfb"
#ifndef Ckb_Protocol_CellInput_identifier
#define Ckb_Protocol_CellInput_identifier flatbuffers_identifier
#endif
#define Ckb_Protocol_CellInput_type_hash ((flatbuffers_thash_t)0xb33adf21)
#define Ckb_Protocol_CellInput_type_identifier "\x21\xdf\x3a\xb3"
#ifndef Ckb_Protocol_CellOutput_identifier
#define Ckb_Protocol_CellOutput_identifier flatbuffers_identifier
#endif
#define Ckb_Protocol_CellOutput_type_hash ((flatbuffers_thash_t)0xfdbc155e)
#define Ckb_Protocol_CellOutput_type_identifier "\x5e\x15\xbc\xfd"
#ifndef Ckb_Protocol_Script_identifier
#define Ckb_Protocol_Script_identifier flatbuffers_identifier
#endif
#define Ckb_Protocol_Script_type_hash ((flatbuffers_thash_t)0x4e9309a8)
#define Ckb_Protocol_Script_type_identifier "\xa8\x09\x93\x4e"
#ifndef Ckb_Protocol_RelayMessage_identifier
#define Ckb_Protocol_RelayMessage_identifier flatbuffers_identifier
#endif
#define Ckb_Protocol_RelayMessage_type_hash ((flatbuffers_thash_t)0x3b5fe0eb)
#define Ckb_Protocol_RelayMessage_type_identifier "\xeb\xe0\x5f\x3b"
#ifndef Ckb_Protocol_CompactBlock_identifier
#define Ckb_Protocol_CompactBlock_identifier flatbuffers_identifier
#endif
#define Ckb_Protocol_CompactBlock_type_hash ((flatbuffers_thash_t)0x22848a39)
#define Ckb_Protocol_CompactBlock_type_identifier "\x39\x8a\x84\x22"
#ifndef Ckb_Protocol_PrefilledTransaction_identifier
#define Ckb_Protocol_PrefilledTransaction_identifier flatbuffers_identifier
#endif
#define Ckb_Protocol_PrefilledTransaction_type_hash ((flatbuffers_thash_t)0xbedd9968)
#define Ckb_Protocol_PrefilledTransaction_type_identifier "\x68\x99\xdd\xbe"
#ifndef Ckb_Protocol_GetBlockTransactions_identifier
#define Ckb_Protocol_GetBlockTransactions_identifier flatbuffers_identifier
#endif
#define Ckb_Protocol_GetBlockTransactions_type_hash ((flatbuffers_thash_t)0xeb251d0b)
#define Ckb_Protocol_GetBlockTransactions_type_identifier "\x0b\x1d\x25\xeb"
#ifndef Ckb_Protocol_BlockTransactions_identifier
#define Ckb_Protocol_BlockTransactions_identifier flatbuffers_identifier
#endif
#define Ckb_Protocol_BlockTransactions_type_hash ((flatbuffers_thash_t)0xddcba841)
#define Ckb_Protocol_BlockTransactions_type_identifier "\x41\xa8\xcb\xdd"
#ifndef Ckb_Protocol_GetBlockProposal_identifier
#define Ckb_Protocol_GetBlockProposal_identifier flatbuffers_identifier
#endif
#define Ckb_Protocol_GetBlockProposal_type_hash ((flatbuffers_thash_t)0xabffa66c)
#define Ckb_Protocol_GetBlockProposal_type_identifier "\x6c\xa6\xff\xab"
#ifndef Ckb_Protocol_BlockProposal_identifier
#define Ckb_Protocol_BlockProposal_identifier flatbuffers_identifier
#endif
#define Ckb_Protocol_BlockProposal_type_hash ((flatbuffers_thash_t)0x8523d6b6)
#define Ckb_Protocol_BlockProposal_type_identifier "\xb6\xd6\x23\x85"


typedef uint8_t Ckb_Protocol_SyncPayload_union_type_t;
__flatbuffers_define_integer_type(Ckb_Protocol_SyncPayload, Ckb_Protocol_SyncPayload_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, Ckb_Protocol_SyncPayload)
#define Ckb_Protocol_SyncPayload_NONE ((Ckb_Protocol_SyncPayload_union_type_t)UINT8_C(0))
#define Ckb_Protocol_SyncPayload_GetHeaders ((Ckb_Protocol_SyncPayload_union_type_t)UINT8_C(1))
#define Ckb_Protocol_SyncPayload_Headers ((Ckb_Protocol_SyncPayload_union_type_t)UINT8_C(2))
#define Ckb_Protocol_SyncPayload_GetBlocks ((Ckb_Protocol_SyncPayload_union_type_t)UINT8_C(3))
#define Ckb_Protocol_SyncPayload_Block ((Ckb_Protocol_SyncPayload_union_type_t)UINT8_C(4))

static inline const char *Ckb_Protocol_SyncPayload_type_name(Ckb_Protocol_SyncPayload_union_type_t type)
{
    switch (type) {
    case Ckb_Protocol_SyncPayload_NONE: return "NONE";
    case Ckb_Protocol_SyncPayload_GetHeaders: return "GetHeaders";
    case Ckb_Protocol_SyncPayload_Headers: return "Headers";
    case Ckb_Protocol_SyncPayload_GetBlocks: return "GetBlocks";
    case Ckb_Protocol_SyncPayload_Block: return "Block";
    default: return "";
    }
}

static inline int Ckb_Protocol_SyncPayload_is_known_type(Ckb_Protocol_SyncPayload_union_type_t type)
{
    switch (type) {
    case Ckb_Protocol_SyncPayload_NONE: return 1;
    case Ckb_Protocol_SyncPayload_GetHeaders: return 1;
    case Ckb_Protocol_SyncPayload_Headers: return 1;
    case Ckb_Protocol_SyncPayload_GetBlocks: return 1;
    case Ckb_Protocol_SyncPayload_Block: return 1;
    default: return 0;
    }
}


struct Ckb_Protocol_SyncMessage_table { uint8_t unused__; };

static inline size_t Ckb_Protocol_SyncMessage_vec_len(Ckb_Protocol_SyncMessage_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Ckb_Protocol_SyncMessage_table_t Ckb_Protocol_SyncMessage_vec_at(Ckb_Protocol_SyncMessage_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Ckb_Protocol_SyncMessage_table_t, vec, i, 0)
__flatbuffers_table_as_root(Ckb_Protocol_SyncMessage)

__flatbuffers_define_union_field(flatbuffers_, 1, Ckb_Protocol_SyncMessage, payload, Ckb_Protocol_SyncPayload, 0)

struct Ckb_Protocol_Bytes_table { uint8_t unused__; };

static inline size_t Ckb_Protocol_Bytes_vec_len(Ckb_Protocol_Bytes_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Ckb_Protocol_Bytes_table_t Ckb_Protocol_Bytes_vec_at(Ckb_Protocol_Bytes_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Ckb_Protocol_Bytes_table_t, vec, i, 0)
__flatbuffers_table_as_root(Ckb_Protocol_Bytes)

__flatbuffers_define_vector_field(0, Ckb_Protocol_Bytes, seq, flatbuffers_uint8_vec_t, 0)

struct Ckb_Protocol_GetHeaders_table { uint8_t unused__; };

static inline size_t Ckb_Protocol_GetHeaders_vec_len(Ckb_Protocol_GetHeaders_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Ckb_Protocol_GetHeaders_table_t Ckb_Protocol_GetHeaders_vec_at(Ckb_Protocol_GetHeaders_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Ckb_Protocol_GetHeaders_table_t, vec, i, 0)
__flatbuffers_table_as_root(Ckb_Protocol_GetHeaders)

__flatbuffers_define_scalar_field(0, Ckb_Protocol_GetHeaders, version, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_vector_field(1, Ckb_Protocol_GetHeaders, block_locator_hashes, Ckb_Protocol_Bytes_vec_t, 0)
__flatbuffers_define_table_field(2, Ckb_Protocol_GetHeaders, hash_stop, Ckb_Protocol_Bytes_table_t, 0)

struct Ckb_Protocol_GetBlocks_table { uint8_t unused__; };

static inline size_t Ckb_Protocol_GetBlocks_vec_len(Ckb_Protocol_GetBlocks_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Ckb_Protocol_GetBlocks_table_t Ckb_Protocol_GetBlocks_vec_at(Ckb_Protocol_GetBlocks_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Ckb_Protocol_GetBlocks_table_t, vec, i, 0)
__flatbuffers_table_as_root(Ckb_Protocol_GetBlocks)

__flatbuffers_define_vector_field(0, Ckb_Protocol_GetBlocks, block_hashes, Ckb_Protocol_Bytes_vec_t, 0)

struct Ckb_Protocol_Headers_table { uint8_t unused__; };

static inline size_t Ckb_Protocol_Headers_vec_len(Ckb_Protocol_Headers_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Ckb_Protocol_Headers_table_t Ckb_Protocol_Headers_vec_at(Ckb_Protocol_Headers_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Ckb_Protocol_Headers_table_t, vec, i, 0)
__flatbuffers_table_as_root(Ckb_Protocol_Headers)

__flatbuffers_define_vector_field(0, Ckb_Protocol_Headers, headers, Ckb_Protocol_Header_vec_t, 0)

struct Ckb_Protocol_Header_table { uint8_t unused__; };

static inline size_t Ckb_Protocol_Header_vec_len(Ckb_Protocol_Header_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Ckb_Protocol_Header_table_t Ckb_Protocol_Header_vec_at(Ckb_Protocol_Header_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Ckb_Protocol_Header_table_t, vec, i, 0)
__flatbuffers_table_as_root(Ckb_Protocol_Header)

__flatbuffers_define_scalar_field(0, Ckb_Protocol_Header, version, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_table_field(1, Ckb_Protocol_Header, parent_hash, Ckb_Protocol_Bytes_table_t, 0)
__flatbuffers_define_scalar_field(2, Ckb_Protocol_Header, timestamp, flatbuffers_uint64, uint64_t, UINT64_C(0))
__flatbuffers_define_scalar_field(3, Ckb_Protocol_Header, number, flatbuffers_uint64, uint64_t, UINT64_C(0))
__flatbuffers_define_table_field(4, Ckb_Protocol_Header, txs_commit, Ckb_Protocol_Bytes_table_t, 0)
__flatbuffers_define_table_field(5, Ckb_Protocol_Header, txs_proposal, Ckb_Protocol_Bytes_table_t, 0)
__flatbuffers_define_table_field(6, Ckb_Protocol_Header, difficulty, Ckb_Protocol_Bytes_table_t, 0)
__flatbuffers_define_scalar_field(7, Ckb_Protocol_Header, nonce, flatbuffers_uint64, uint64_t, UINT64_C(0))
__flatbuffers_define_table_field(8, Ckb_Protocol_Header, proof, Ckb_Protocol_Bytes_table_t, 0)
__flatbuffers_define_table_field(9, Ckb_Protocol_Header, cellbase_id, Ckb_Protocol_Bytes_table_t, 0)
__flatbuffers_define_table_field(10, Ckb_Protocol_Header, uncles_hash, Ckb_Protocol_Bytes_table_t, 0)

struct Ckb_Protocol_Block_table { uint8_t unused__; };

static inline size_t Ckb_Protocol_Block_vec_len(Ckb_Protocol_Block_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Ckb_Protocol_Block_table_t Ckb_Protocol_Block_vec_at(Ckb_Protocol_Block_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Ckb_Protocol_Block_table_t, vec, i, 0)
__flatbuffers_table_as_root(Ckb_Protocol_Block)

__flatbuffers_define_table_field(0, Ckb_Protocol_Block, header, Ckb_Protocol_Header_table_t, 0)
__flatbuffers_define_vector_field(1, Ckb_Protocol_Block, uncles, Ckb_Protocol_UncleBlock_vec_t, 0)
__flatbuffers_define_vector_field(2, Ckb_Protocol_Block, commit_transactions, Ckb_Protocol_Transaction_vec_t, 0)
__flatbuffers_define_vector_field(3, Ckb_Protocol_Block, proposal_transactions, Ckb_Protocol_Bytes_vec_t, 0)

struct Ckb_Protocol_UncleBlock_table { uint8_t unused__; };

static inline size_t Ckb_Protocol_UncleBlock_vec_len(Ckb_Protocol_UncleBlock_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Ckb_Protocol_UncleBlock_table_t Ckb_Protocol_UncleBlock_vec_at(Ckb_Protocol_UncleBlock_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Ckb_Protocol_UncleBlock_table_t, vec, i, 0)
__flatbuffers_table_as_root(Ckb_Protocol_UncleBlock)

__flatbuffers_define_table_field(0, Ckb_Protocol_UncleBlock, header, Ckb_Protocol_Header_table_t, 0)
__flatbuffers_define_table_field(1, Ckb_Protocol_UncleBlock, cellbase, Ckb_Protocol_Transaction_table_t, 0)
__flatbuffers_define_vector_field(2, Ckb_Protocol_UncleBlock, proposal_transactions, Ckb_Protocol_Bytes_vec_t, 0)

struct Ckb_Protocol_Transaction_table { uint8_t unused__; };

static inline size_t Ckb_Protocol_Transaction_vec_len(Ckb_Protocol_Transaction_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Ckb_Protocol_Transaction_table_t Ckb_Protocol_Transaction_vec_at(Ckb_Protocol_Transaction_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Ckb_Protocol_Transaction_table_t, vec, i, 0)
__flatbuffers_table_as_root(Ckb_Protocol_Transaction)

__flatbuffers_define_scalar_field(0, Ckb_Protocol_Transaction, version, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_vector_field(1, Ckb_Protocol_Transaction, deps, Ckb_Protocol_OutPoint_vec_t, 0)
__flatbuffers_define_vector_field(2, Ckb_Protocol_Transaction, inputs, Ckb_Protocol_CellInput_vec_t, 0)
__flatbuffers_define_vector_field(3, Ckb_Protocol_Transaction, outputs, Ckb_Protocol_CellOutput_vec_t, 0)

struct Ckb_Protocol_OutPoint_table { uint8_t unused__; };

static inline size_t Ckb_Protocol_OutPoint_vec_len(Ckb_Protocol_OutPoint_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Ckb_Protocol_OutPoint_table_t Ckb_Protocol_OutPoint_vec_at(Ckb_Protocol_OutPoint_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Ckb_Protocol_OutPoint_table_t, vec, i, 0)
__flatbuffers_table_as_root(Ckb_Protocol_OutPoint)

__flatbuffers_define_table_field(0, Ckb_Protocol_OutPoint, hash, Ckb_Protocol_Bytes_table_t, 0)
__flatbuffers_define_scalar_field(1, Ckb_Protocol_OutPoint, index, flatbuffers_uint32, uint32_t, UINT32_C(0))

struct Ckb_Protocol_CellInput_table { uint8_t unused__; };

static inline size_t Ckb_Protocol_CellInput_vec_len(Ckb_Protocol_CellInput_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Ckb_Protocol_CellInput_table_t Ckb_Protocol_CellInput_vec_at(Ckb_Protocol_CellInput_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Ckb_Protocol_CellInput_table_t, vec, i, 0)
__flatbuffers_table_as_root(Ckb_Protocol_CellInput)

__flatbuffers_define_table_field(0, Ckb_Protocol_CellInput, hash, Ckb_Protocol_Bytes_table_t, 0)
__flatbuffers_define_scalar_field(1, Ckb_Protocol_CellInput, index, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_table_field(2, Ckb_Protocol_CellInput, unlock, Ckb_Protocol_Script_table_t, 0)

struct Ckb_Protocol_CellOutput_table { uint8_t unused__; };

static inline size_t Ckb_Protocol_CellOutput_vec_len(Ckb_Protocol_CellOutput_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Ckb_Protocol_CellOutput_table_t Ckb_Protocol_CellOutput_vec_at(Ckb_Protocol_CellOutput_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Ckb_Protocol_CellOutput_table_t, vec, i, 0)
__flatbuffers_table_as_root(Ckb_Protocol_CellOutput)

__flatbuffers_define_scalar_field(0, Ckb_Protocol_CellOutput, capacity, flatbuffers_uint64, uint64_t, UINT64_C(0))
__flatbuffers_define_table_field(1, Ckb_Protocol_CellOutput, data, Ckb_Protocol_Bytes_table_t, 0)
__flatbuffers_define_table_field(2, Ckb_Protocol_CellOutput, lock, Ckb_Protocol_Bytes_table_t, 0)

struct Ckb_Protocol_Script_table { uint8_t unused__; };

static inline size_t Ckb_Protocol_Script_vec_len(Ckb_Protocol_Script_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Ckb_Protocol_Script_table_t Ckb_Protocol_Script_vec_at(Ckb_Protocol_Script_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Ckb_Protocol_Script_table_t, vec, i, 0)
__flatbuffers_table_as_root(Ckb_Protocol_Script)

__flatbuffers_define_scalar_field(0, Ckb_Protocol_Script, version, flatbuffers_uint8, uint8_t, UINT8_C(0))
__flatbuffers_define_vector_field(1, Ckb_Protocol_Script, arguments, Ckb_Protocol_Bytes_vec_t, 0)
__flatbuffers_define_table_field(2, Ckb_Protocol_Script, redeem_script, Ckb_Protocol_Bytes_table_t, 0)
__flatbuffers_define_table_field(3, Ckb_Protocol_Script, redeem_reference, Ckb_Protocol_OutPoint_table_t, 0)
__flatbuffers_define_vector_field(4, Ckb_Protocol_Script, redeem_arguments, Ckb_Protocol_Bytes_vec_t, 0)
typedef uint8_t Ckb_Protocol_RelayPayload_union_type_t;
__flatbuffers_define_integer_type(Ckb_Protocol_RelayPayload, Ckb_Protocol_RelayPayload_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, Ckb_Protocol_RelayPayload)
#define Ckb_Protocol_RelayPayload_NONE ((Ckb_Protocol_RelayPayload_union_type_t)UINT8_C(0))
#define Ckb_Protocol_RelayPayload_CompactBlock ((Ckb_Protocol_RelayPayload_union_type_t)UINT8_C(1))
#define Ckb_Protocol_RelayPayload_Transaction ((Ckb_Protocol_RelayPayload_union_type_t)UINT8_C(2))
#define Ckb_Protocol_RelayPayload_GetBlockTransactions ((Ckb_Protocol_RelayPayload_union_type_t)UINT8_C(3))
#define Ckb_Protocol_RelayPayload_BlockTransactions ((Ckb_Protocol_RelayPayload_union_type_t)UINT8_C(4))
#define Ckb_Protocol_RelayPayload_GetBlockProposal ((Ckb_Protocol_RelayPayload_union_type_t)UINT8_C(5))
#define Ckb_Protocol_RelayPayload_BlockProposal ((Ckb_Protocol_RelayPayload_union_type_t)UINT8_C(6))

static inline const char *Ckb_Protocol_RelayPayload_type_name(Ckb_Protocol_RelayPayload_union_type_t type)
{
    switch (type) {
    case Ckb_Protocol_RelayPayload_NONE: return "NONE";
    case Ckb_Protocol_RelayPayload_CompactBlock: return "CompactBlock";
    case Ckb_Protocol_RelayPayload_Transaction: return "Transaction";
    case Ckb_Protocol_RelayPayload_GetBlockTransactions: return "GetBlockTransactions";
    case Ckb_Protocol_RelayPayload_BlockTransactions: return "BlockTransactions";
    case Ckb_Protocol_RelayPayload_GetBlockProposal: return "GetBlockProposal";
    case Ckb_Protocol_RelayPayload_BlockProposal: return "BlockProposal";
    default: return "";
    }
}

static inline int Ckb_Protocol_RelayPayload_is_known_type(Ckb_Protocol_RelayPayload_union_type_t type)
{
    switch (type) {
    case Ckb_Protocol_RelayPayload_NONE: return 1;
    case Ckb_Protocol_RelayPayload_CompactBlock: return 1;
    case Ckb_Protocol_RelayPayload_Transaction: return 1;
    case Ckb_Protocol_RelayPayload_GetBlockTransactions: return 1;
    case Ckb_Protocol_RelayPayload_BlockTransactions: return 1;
    case Ckb_Protocol_RelayPayload_GetBlockProposal: return 1;
    case Ckb_Protocol_RelayPayload_BlockProposal: return 1;
    default: return 0;
    }
}


struct Ckb_Protocol_RelayMessage_table { uint8_t unused__; };

static inline size_t Ckb_Protocol_RelayMessage_vec_len(Ckb_Protocol_RelayMessage_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Ckb_Protocol_RelayMessage_table_t Ckb_Protocol_RelayMessage_vec_at(Ckb_Protocol_RelayMessage_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Ckb_Protocol_RelayMessage_table_t, vec, i, 0)
__flatbuffers_table_as_root(Ckb_Protocol_RelayMessage)

__flatbuffers_define_union_field(flatbuffers_, 1, Ckb_Protocol_RelayMessage, payload, Ckb_Protocol_RelayPayload, 0)

struct Ckb_Protocol_CompactBlock_table { uint8_t unused__; };

static inline size_t Ckb_Protocol_CompactBlock_vec_len(Ckb_Protocol_CompactBlock_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Ckb_Protocol_CompactBlock_table_t Ckb_Protocol_CompactBlock_vec_at(Ckb_Protocol_CompactBlock_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Ckb_Protocol_CompactBlock_table_t, vec, i, 0)
__flatbuffers_table_as_root(Ckb_Protocol_CompactBlock)

__flatbuffers_define_table_field(0, Ckb_Protocol_CompactBlock, header, Ckb_Protocol_Header_table_t, 0)
__flatbuffers_define_scalar_field(1, Ckb_Protocol_CompactBlock, nonce, flatbuffers_uint64, uint64_t, UINT64_C(0))
__flatbuffers_define_vector_field(2, Ckb_Protocol_CompactBlock, short_ids, Ckb_Protocol_Bytes_vec_t, 0)
__flatbuffers_define_vector_field(3, Ckb_Protocol_CompactBlock, prefilled_transactions, Ckb_Protocol_PrefilledTransaction_vec_t, 0)
__flatbuffers_define_vector_field(4, Ckb_Protocol_CompactBlock, uncles, Ckb_Protocol_UncleBlock_vec_t, 0)
__flatbuffers_define_vector_field(5, Ckb_Protocol_CompactBlock, proposal_transactions, Ckb_Protocol_Bytes_vec_t, 0)

struct Ckb_Protocol_PrefilledTransaction_table { uint8_t unused__; };

static inline size_t Ckb_Protocol_PrefilledTransaction_vec_len(Ckb_Protocol_PrefilledTransaction_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Ckb_Protocol_PrefilledTransaction_table_t Ckb_Protocol_PrefilledTransaction_vec_at(Ckb_Protocol_PrefilledTransaction_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Ckb_Protocol_PrefilledTransaction_table_t, vec, i, 0)
__flatbuffers_table_as_root(Ckb_Protocol_PrefilledTransaction)

__flatbuffers_define_scalar_field(0, Ckb_Protocol_PrefilledTransaction, index, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_table_field(1, Ckb_Protocol_PrefilledTransaction, transaction, Ckb_Protocol_Transaction_table_t, 0)

struct Ckb_Protocol_GetBlockTransactions_table { uint8_t unused__; };

static inline size_t Ckb_Protocol_GetBlockTransactions_vec_len(Ckb_Protocol_GetBlockTransactions_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Ckb_Protocol_GetBlockTransactions_table_t Ckb_Protocol_GetBlockTransactions_vec_at(Ckb_Protocol_GetBlockTransactions_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Ckb_Protocol_GetBlockTransactions_table_t, vec, i, 0)
__flatbuffers_table_as_root(Ckb_Protocol_GetBlockTransactions)

__flatbuffers_define_table_field(0, Ckb_Protocol_GetBlockTransactions, hash, Ckb_Protocol_Bytes_table_t, 0)
__flatbuffers_define_vector_field(1, Ckb_Protocol_GetBlockTransactions, indexes, flatbuffers_uint32_vec_t, 0)

struct Ckb_Protocol_BlockTransactions_table { uint8_t unused__; };

static inline size_t Ckb_Protocol_BlockTransactions_vec_len(Ckb_Protocol_BlockTransactions_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Ckb_Protocol_BlockTransactions_table_t Ckb_Protocol_BlockTransactions_vec_at(Ckb_Protocol_BlockTransactions_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Ckb_Protocol_BlockTransactions_table_t, vec, i, 0)
__flatbuffers_table_as_root(Ckb_Protocol_BlockTransactions)

__flatbuffers_define_table_field(0, Ckb_Protocol_BlockTransactions, hash, Ckb_Protocol_Bytes_table_t, 0)
__flatbuffers_define_vector_field(1, Ckb_Protocol_BlockTransactions, transactions, Ckb_Protocol_Transaction_vec_t, 0)

struct Ckb_Protocol_GetBlockProposal_table { uint8_t unused__; };

static inline size_t Ckb_Protocol_GetBlockProposal_vec_len(Ckb_Protocol_GetBlockProposal_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Ckb_Protocol_GetBlockProposal_table_t Ckb_Protocol_GetBlockProposal_vec_at(Ckb_Protocol_GetBlockProposal_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Ckb_Protocol_GetBlockProposal_table_t, vec, i, 0)
__flatbuffers_table_as_root(Ckb_Protocol_GetBlockProposal)

__flatbuffers_define_scalar_field(0, Ckb_Protocol_GetBlockProposal, block_number, flatbuffers_uint64, uint64_t, UINT64_C(0))
__flatbuffers_define_vector_field(1, Ckb_Protocol_GetBlockProposal, proposal_transactions, Ckb_Protocol_Bytes_vec_t, 0)

struct Ckb_Protocol_BlockProposal_table { uint8_t unused__; };

static inline size_t Ckb_Protocol_BlockProposal_vec_len(Ckb_Protocol_BlockProposal_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Ckb_Protocol_BlockProposal_table_t Ckb_Protocol_BlockProposal_vec_at(Ckb_Protocol_BlockProposal_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Ckb_Protocol_BlockProposal_table_t, vec, i, 0)
__flatbuffers_table_as_root(Ckb_Protocol_BlockProposal)

__flatbuffers_define_vector_field(0, Ckb_Protocol_BlockProposal, transactions, Ckb_Protocol_Transaction_vec_t, 0)

#include "flatcc/flatcc_epilogue.h"
#endif /* PROTOCOL_READER_H */
